gantt
    title Project Plan
    dateFormat  YYYY-MM-DD
    section Phase 1
    Task 1 :done, t1, 2025-01-01, 2025-01-10
    Task 2 :active, t2, after t1, 7d
    section Phase 2
    Task 3 : t3, after t2, 10d
    Task 4 :crit, t4, after t3, 5d